### ISSUE TITLE
z3 error

### ISSUE THREAD

**Issue by z971586668** [RafaelTupynamba/SMTSampler#1]
Hi,
I was trying to use your tool and got this error when compling z3
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "z3/scripts/mk_util.py", line 2674, in mk_makefile
    c.mk_makefile(out)
  File "z3/scripts/mk_util.py", line 1103, in mk_makefile
    Component.mk_makefile(self, out)
  File "z3/scripts/mk_util.py", line 1050, in mk_makefile
    self.add_cpp_rules(out, include_defs, cppfile)
  File "z3/scripts/mk_util.py", line 1007, in add_cpp_rules
    self.add_rule_for_each_include(out, cppfile)
  File "z3/scripts/mk_util.py", line 986, in add_rule_for_each_include
    owner = self.find_file(include, fullname)
  File "z3/scripts/mk_util.py", line 970, in find_file
    raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name))
mk_exception.MKException: "Failed to find include file 'api_context.h' for 'src/model/model.cpp' when processing 'model'."

**Comment by RafaelTupynamba** [comment]
Please apply the patch to file mk_util.py as described in the README:

cp ../SMTSampler/z3-patch/mk_util.py scripts/mk_util.py
